---
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API
  ansible.builtin.uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body_format: json
    body:
      "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    status_code: 201, 308
    headers:
      content-type: application/x-www-form-urlencoded
  register: falcon_api_oauth2_token

- name: CrowdStrike Falcon | Auto-discover CrowdStrike Cloud Region
  ansible.builtin.set_fact:
      falcon_cloud: "{{ falcon_cloud_urls[falcon_api_oauth2_token.x_cs_region] }}"
  when:
    - falcon_cloud_autodiscover
    - falcon_api_oauth2_token.x_cs_region|length > 0
    
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API
  ansible.builtin.uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body_format: json
    body:
      "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    status_code: 201, 308
    headers:
      content-type: application/x-www-form-urlencoded
  register: falcon_api_oauth2_token

# Block when falcon_sensor_update_policy_name is supplied
- block:
  - name: "CrowdStrike Falcon | Override falcon_sensor_version_decrement when falcon_sensor_update_policy_name supplied"
    ansible.builtin.set_fact:
      falcon_sensor_version_decrement: 0

  - name: "CrowdStrike Falcon | Build Sensor Update Policy API Query"
    ansible.builtin.set_fact:
      falcon_sensor_update_policy_query: "{{ 'platform_name:\"' + falcon_sensor_update_policy_platform + '\"+name.raw:\"' + falcon_sensor_update_policy_name + '\"' }}"

  - name: "CrowdStrike Falcon | Search for Sensor Update Policy"
    ansible.builtin.uri:
      url: "https://{{ falcon_cloud }}/policy/combined/sensor-update/v2?filter={{ falcon_sensor_update_policy_query | urlencode }}"
      method: GET
      return_content: true
      headers:
        authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
        Content-Type: application/json
    register: falcon_sensor_update_policy_info

  - name: "CrowdStrike Falcon | Validate Sensor Update Policy request"
    ansible.builtin.fail:
      msg: "No Falcon Sensor Update Policy with name: {{ falcon_sensor_update_policy_name }} was found!"
    when: falcon_sensor_update_policy_info.json.resources[0] is not defined

  - name: "CrowdStrike Falcon | Validate Sensor Update Policy request for aarch64 architectures"
    ansible.builtin.fail:
      msg: "No Falcon Sensor Update Policy with name: {{ falcon_sensor_update_policy_name }} and enabled for aarch64 was found!"
    when:
      - falcon_sensor_update_policy_info.json.resources[0].settings.variants[0] is not defined
      - ansible_machine == "aarch64"

  - name: "CrowdStrike Falcon | Get the Falcon Sensor version from Update Policy"
    ansible.builtin.set_fact:
      falcon_sensor_update_policy_package_version: "{{ falcon_sensor_update_policy_info.json.resources[0].settings.sensor_version }}"
    when: ansible_machine != "aarch64"

  - name: "CrowdStrike Falcon | Get the Falcon Sensor version from Update Policy for aarch64 architecture"
    ansible.builtin.set_fact:
      falcon_sensor_update_policy_package_version: "{{ falcon_sensor_update_policy_info.json.resources[0].settings.variants[0].sensor_version }}"
    when: ansible_machine == "aarch64"

  - name: "CrowdStrike Falcon | Build API Sensor Query based on Sensor Update Policy"
    ansible.builtin.set_fact:
      falcon_os_query: "{{ 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"+version:\"' + falcon_sensor_update_policy_package_version + '\"' }}"

  when: falcon_sensor_update_policy_name

- name: "CrowdStrike Falcon | Build API Sensor Query"
  ansible.builtin.set_fact:
    falcon_os_query: "{{ 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"' }}"
  when: not falcon_sensor_update_policy_name

- name: CrowdStrike Falcon | Get list of filtered Falcon sensors
  ansible.builtin.uri:
    url: "https://{{ falcon_cloud }}/sensors/combined/installers/v1?filter={{ falcon_os_query | urlencode }}"
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
      Content-Type: application/json
  register: falcon_api_installer_list

- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package
  ansible.builtin.get_url:
    url: "https://{{ falcon_cloud }}/sensors/entities/download-installer/v1?id={{ falcon_api_installer_list.json.resources[falcon_sensor_version_decrement | int].sha256 }}"
    dest: "{{ falcon_install_temp_directory.path }}"
    checksum: "sha256:{{ falcon_api_installer_list.json.resources[falcon_sensor_version_decrement | int].sha256 }}"
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  changed_when: false
  register: falcon_sensor_download

- name: CrowdStrike Falcon | Set full file download path
  ansible.builtin.set_fact:
    falcon_sensor_pkg: "{{ falcon_sensor_download.dest }}"
