---
- block:
  - name: CrowdStrike Falcon | Set default sensor name
    ansible.builtin.set_fact:
      installed_sensor: falcon-sensor
    when:
      - ansible_pkg_mgr in linux_packagers

  - name: CrowdStrike Falcon | Set default sensor name for non-Windows installations
    ansible.builtin.set_fact:
      falcon_sensor_pkg: "{{ installed_sensor }}"
    when:
      - ansible_pkg_mgr in linux_packagers
      - falcon_sensor_download is not defined

  - name: CrowdStrike Falcon | Transfer CrowdStrike Falcon RPM GPG key file
    ansible.builtin.copy:
      src: "{{ falcon_gpg_key }}"
      dest: "{{ falcon_install_temp_directory.path }}/{{ falcon_gpg_key }}"
      mode: 0644
    changed_when: no
    when:
      - falcon_gpg_key_check

  - name: CrowdStrike Falcon | Import CrowdStrike Falcon RPM GPG key from file
    ansible.builtin.rpm_key:
      state: present
      key: '{{ falcon_install_temp_directory.path }}/{{ falcon_gpg_key }}'
    changed_when: no
    when:
      - falcon_gpg_key_check
      - ansible_pkg_mgr in rpm_packagers

  - name: CrowdStrike Falcon | Import CrowdStrike Falcon APT GPG key from file
    ansible.builtin.apt_key:
      file: '{{ falcon_install_temp_directory.path }}/{{ falcon_gpg_key }}'
      state: present
    changed_when: no
    when:
      - falcon_gpg_key_check
      - ansible_pkg_mgr in dpkg_packagers

  - name: CrowdStrike Falcon | Install Falcon Sensor Package (Linux)
    ansible.builtin.package:
      deb: "{{ falcon_sensor_pkg if (ansible_pkg_mgr in dpkg_packagers) else omit }}"
      name: "{{ falcon_sensor_pkg if (ansible_pkg_mgr in rpm_packagers) else omit }}"
      state: present
    when:
      - ansible_pkg_mgr in linux_packagers

  - name: CrowdStrike Falcon | Install Falcon Sensor .pkg Package (macOS)
    ansible.builtin.command: "/usr/sbin/installer -pkg {{ falcon_sensor_pkg }} -target /"
    args:
      creates: "/Applications/Falcon.app/Contents/Resources/falconctl"
    when:
      - ansible_distribution == "MacOSX"

  - name: CrowdStrike Falcon | Verify Falcon Package Is Installed
    ansible.builtin.package_facts:
      manager: auto
    when: ansible_distribution != "MacOSX"
    
  - name: CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)
    command: "/opt/CrowdStrike/falconctl -s -f --cid={{ falcon_cid }}"
    when:
      - falcon_cid
      - ansible_distribution != "MacOSX"
      
  - name: CrowdStrike Falcon Installer | Starting Falcon Sensor Daemon (Linux)
    service:
      name: falcon-sensor
      state: started
      enabled: yes
    when:
      - falcon_cid
      - ansible_distribution != "MacOSX"
